def exception_generator(msg):
    yield {'exception': msg}
